### ISSUE TITLE
Miss head file for Interface1Service and Interface1Client

### ISSUE THREAD

**Issue by cometdlut** [nkh-lab/ndk-capi-hello-world#1]
Hello,
Your repo miss head files for Interface1Service and Interface1Client.

**Comment by nkh-lab** [comment]
Did you try to clone submodule projects? After cloning they should be in external/genivi-capi-someip-examples/include (https://github.com/nkh-lab/genivi-capi-someip-examples/tree/0be353d0a07f5cc4e4983a42cd2415725ae0506a/include).

**Comment by nkh-lab** [comment]
Not an issue.
