### ISSUE TITLE
androin and ubuntu communicate with soemip

### ISSUE THREAD

**Issue by fengtuo58** [nkh-lab/ndk-capi-hello-world#2]
hi, how to make the androin and ubuntu host communicate with someip rather than two service on androin?  I am a novice to androin so please guide me about androin config to communicate betwen ndroin and ubuntu host. Thanks

**Comment by fengtuo58** [comment]
@nkh-lab

**Comment by nkh-lab** [comment]
Hi, it is possible, you need to switch communication from local socket usage to TCP or UDP by providing corresponding configuration to your server and client. You can find needed information here https://github.com/COVESA/vsomeip/wiki/vsomeip-in-10-minutes and here https://github.com/COVESA/vsomeip/issues/29.
